# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mine' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

	
  pod "RealmSwift"
pod 'Quick'
    	pod 'Nimble'

  target 'MineTests' do
    inherit! :search_paths
    
	
  end

end



